import "@/style/globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Main from "@/components/Main";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col min-h-full">
          <Header />
          <Main>{children}</Main>
          <Footer />
        </div>
        <div id="modal-root" />
      </body>
    </html>
  );
}
